<div class="edit-form">
    <form action="<?php /** @noinspection PhpUndefinedVariableInspection */
    echo $action ?>" method="post">
        <label for="name">Name Of Todo</label>
        <input type="text" name="name" placeholder="Name goes here"/>

        <label for="description">Description of Todo</label>
        <textarea name="description" id="" cols="200" rows="10" placeholder="description"></textarea>

        <input type="submit" value="Submit">
    </form>
</div>