<?php
/**
 * @var $todoList \Controller\TodoController listAction();
 */
?>
<div class="lead">
    <?php foreach ($todoList as $todo): ?>
        <div class="todo">
            <div class="heading">
                <h2><?php echo $todo['name']; ?></h2>
                <div class="actions">
                    <a href="/todo/edit/<?php echo $todo['id']; ?>" class="edit">edit</a>
                    <a href="/todo/remove/<?php echo $todo['id']; ?>" class="remove">remove</a>
                </div>
            </div>
            <?php if($todo['description']): ?>
            <div class="description"><?php echo $todo['description'] ?></div>
            <?php endif; ?>
            <?php if(!empty($todo['points'])): ?>
            <div class="points">
                <ul>
                    <?php foreach($todo['points'] as $point): ?>
                    <li><?php echo $point; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>