<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To-dos List</title>
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="/css/main.css">
</head>
<body>
<div class="header">
    <?php include ROOT . '/app/templates/header.phtml'; ?>
</div>
<div class="content">
    <h1>404</h1>
    <span>there is no such page</span>
</div>
<div class="footer">
    <?php include ROOT . '/app/templates/footer.phtml'; ?>
</div>
</body>
</html>