<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To-dos List</title>
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/form.css">
    <script type="text/javascript" src="/js/main.js"></script>
</head>
<body>
<div class="header">
    <?php include ROOT . '/app/templates/header.phtml'; ?>
</div>
<div class="content">
    <?php if (isset($content)) {
        /** @noinspection PhpIncludeInspection */
        include ROOT . '/app/templates/' . $content . '.phtml';
    } ?>
</div>
<div class="footer">
    <?php include ROOT . '/app/templates/footer.phtml'; ?>
</div>
</body>
</html>